### ISSUE TITLE
Change WIR notification channel

### ISSUE THREAD

**Issue by 0xazure** [new-xkit/NewXKitBot#5]
Given our [Gitter dev channel](https://gitter.im/new-xkit/XKit) is becoming more active with members outside the core team, it doesn't make sense to have the notification that a new WIR has been drafted to @ all in this channel, particularly as only a small subset of users in this channel can do anything about the notification.

I would propose moving the notification message to the org channel, which will also increase visibility for the notification as the org channel is typically less active than our dev chat.

**Comment by Wolvan** [comment]
Sure, that should be an easy enough change. I'll work on that once I am back home next week (remind me to do that please, @0xazure)

**Comment by Wolvan** [comment]
Alright, I changed it to be in the repo chat from now on. Closing this issue.

**Comment by 0xazure** [comment]
>  repo chat

I hope you mean org chat.

Since the code hasn't been included in the repo, and I have no way to verify if the change has actually been made until Friday, could you give a summary of what you changed?

**Comment by Wolvan** [comment]
Yeah I meant org chat, sorry. I just changed "new-xkit/XKit" to "new-xkit", see the org chat for a test earlier this morning
